# ScraperAPI api key for rotational proxy
api_key: 0ad5cbd610bf4d2f9a32995f2804791d

# Njuškalo url to scrape
url_to_scrape: https://www.njuskalo.hr/?ctl=search_ads&keywords=concept+2

# Database info
db_username: user1
db_password: password1
db_host: localhost

# Slack channel ID and webhook url
channel_id: C1H9RESGL
webhook_url: https://hooks.slack.com/services/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