version: "3.9"
services:
  db:
    container_name: postgres_container
    image: postgres:15.0-alpine3.16
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - webnet

  app:
    build: .
    environment:
      DB_HOST: db
    networks:
      - webnet

volumes:
  postgres:

networks:
  webnet: